# **Part 3: Combining DataFrames, Text & Date Methods in Pandas**

### **Dataset Introduction**

In this project, we will work with the Palmer Penguins dataset, which contains measurements of penguins observed on islands near Antarctica.

Please download the dataset [penguins.csv](https://drive.google.com/file/d/1dv8A8v_sdf29p1At40S7KBslJPmBA3e9/view?usp=sharing) or from canvas.

### **Dataset Description**

Each row represents a penguin, and columns include:

- species – Penguin species
- island – Island where the penguin was found
- bill_length_mm – Bill length (mm)
- bill_depth_mm – Bill depth (mm)
- flipper_length_mm – Flipper length (mm)
- body_mass_g – Body mass (grams)
- sex – Sex of the penguin

Some values are missing, which makes this dataset ideal for practicing missing data handling.

### **Load the Dataset**

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("penguins.csv")
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

### **Part 1 — Basic Pandas Commands**

Q1. Display the dataset information.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [5]:
# DO NOT RUN THIS

Q2. Display the number of unique species and unique islands.

In [6]:
df["species"].nunique()

3

In [7]:
df["island"].nunique()

3

In [8]:
# DO NOT RUN THIS

In [9]:
# DO NOT RUN THIS

### **Part 2 — GroupBy Basics**

Q3. Compute the average body mass for each species.

In [10]:
df.groupby("species")["body_mass_g"].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [11]:
# DO NOT RUN THIS

Q4. Compute the average flipper length for each island.

In [12]:
df.groupby("island")["flipper_length_mm"].mean()

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [13]:
# DO NOT RUN THIS

Q5. For each species, find the minimum, maximum, and mean of bill_length_mm.

In [14]:
df.groupby("species")["bill_length_mm"].agg(["min", "max", "mean"])

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

In [15]:
# DO NOT RUN THIS

Q6. For each species–island combination, find the number of non-missing body mass measurements.

In [16]:
df.groupby(["species", "island"])["body_mass_g"].count()

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

In [17]:
# DO NOT RUN THIS

Q7. Identify the species with the largest average body mass.

In [18]:
df.groupby("species")["body_mass_g"].mean().idxmax()

'Gentoo'

In [19]:
# DO NOT RUN THIS

Q8. Sort islands by descending average flipper length.

In [20]:
df.groupby("island")["flipper_length_mm"].mean().sort_values(ascending=False)

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [21]:
# DO NOT RUN THIS

Q9.Find species–island groups with at least 20 penguins.

In [22]:
groups = df.groupby(["species", "island"]).size()
groups[groups >= 20]

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     52
Chinstrap  Dream         68
Gentoo     Biscoe       124
dtype: int64

In [23]:
# DO NOT RUN THIS

Q10. For each species, compute:

- average body mass
- average flipper length

In [24]:
df.groupby("species")[["body_mass_g", "flipper_length_mm"]].mean()

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

In [25]:
# DO NOT RUN THIS

Q11. For each island, compute:

- count of penguins
- mean body mass
- standard deviation of body mass

In [26]:
df.groupby("island").agg(
    count=("species", "size"),
    mean_body_mass=("body_mass_g", "mean"),
    std_body_mass=("body_mass_g", "std")
)

           count  mean_body_mass  std_body_mass
island
Biscoe       168     4716.017964     782.855743
Dream        124     3712.903226     416.644112
Torgersen     52     3706.372549     445.107940

In [27]:
# DO NOT RUN THIS

### **Part 3 — Combining DataFrames + GroupBy**

Q12. Create the following penguin_regions dataframe and merge with penguins.



```
{
    'island': ['Biscoe', 'Dream', 'Torgersen'],
    'region': ['Antarctica', 'Antarctica', 'Antarctica']
}
```

In [28]:
penguin_regions = pd.DataFrame({
    "island": ["Biscoe", "Dream", "Torgersen"],
    "region": ["Antarctica", "Antarctica", "Antarctica"]
})

df = df.merge(penguin_regions, on="island", how="left")
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,Antarctica
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,Antarctica
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,Antarctica
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,Antarctica
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,Antarctica

Q13. Compute the average body mass per region.

In [29]:
df.groupby("region")["body_mass_g"].mean()

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

In [30]:
# DO NOT RUN THIS

Q14.Compute the average body_mass_g grouped by species, and then compute the overall average body_mass_g without grouping.

- Why are the species-level averages different from the overall average?
- What does this tell you about how groupby() changes the interpretation of results?

In [31]:
df.groupby("species")["body_mass_g"].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [32]:
# DO NOT RUN THIS

In [33]:
# DO NOT RUN THIS

Your Explanation:

### **Part 4 — GroupBy with Text Methods**

Q15. Create species_lower with lowercase species names.

In [34]:
df["species_lower"] = df["species"].str.lower()
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region,species_lower
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,Antarctica,adelie
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,Antarctica,adelie
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,Antarctica,adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,Antarctica,adelie
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,Antarctica,adelie

In [35]:
# DO NOT RUN THIS

Q16. After creating the species_lower column, you want to verify that converting text to lowercase did not change the number of observations for each species.

Compute the number of penguins for each value in species_lower.

In [36]:
df.groupby("species_lower").size()

species_lower
adelie       152
chinstrap     68
gentoo       124
dtype: int64

In [37]:
# DO NOT RUN THIS

Q17. Create penguin_observations, with the following data.

observation_date': '2019-01-15', '2019-02-20', '2020-01-05', '2020-03-18'

In [38]:
penguin_observations = pd.DataFrame({
    "observation_date": [
        "2019-01-15",
        "2019-02-20",
        "2020-01-05",
        "2020-03-18"
    ]
})

penguin_observations

  observation_date
0       2019-01-15
1       2019-02-20
2       2020-01-05
3       2020-03-18

In [39]:
# DO NOT RUN THIS

Q19. Convert observation_date to datetime and extract year.

In [40]:
penguin_observations["observation_date"] = pd.to_datetime(
    penguin_observations["observation_date"]
)

penguin_observations["year"] = penguin_observations["observation_date"].dt.year

penguin_observations

  observation_date  year
0       2019-01-15  2019
1       2019-02-20  2019
2       2020-01-05  2020
3       2020-03-18  2020

In [41]:
# DO NOT RUN THIS

Q20. Merge with original penguins dataframe and show the head.

In [42]:
df = df.merge(
    penguin_observations,
    left_index=True,
    right_index=True,
    how="left"
)

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region,species_lower,observation_date,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,Antarctica,adelie,2019-01-15,2019.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,Antarctica,adelie,2019-02-20,2019.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,Antarctica,adelie,2020-01-05,2020.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,Antarctica,adelie,2020-03-18,2020.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,Antarctica,adelie,NaT,NaN

In [43]:
# DO NOT RUN THIS